FROM rust:1.69.0 as builder

ENV RUST_BACKTRACE=full \
    USERNAME=spiffodev

# Grab scripts
COPY .scripts/*sh /tmp/scripts/

# Set up dependencies
RUN rustup component add clippy \
    && rustup component add rustfmt \
    && add-apt-repository multiverse \
    && dpkg --add-architecture i386 \
    && apt-get -y update --no-install-recommends \
    && apt-get -y install --no-install-recommends lib32gcc1 steamcmd \
    && /bin/bash /tmp/scripts/perms.sh "${USERNAME}" "${USER_UID}" "${USER_GID}" \
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/bin/apt/lists/* /tmp/scripts

USER $USERNAME